[package]
name = "spcapi"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
chronoutil = "0.2"
ndarray = "0.15"
rust_decimal = "1.28"
rust_decimal_macros = "1.28"